<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SystemNotification;

class RvmNotificationCategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $notifications = [
            // RVM Status Change Notifications (High Priority)
            [
                'title' => 'RVM Status Changed to Active',
                'message' => 'RVM {rvm_name} is now operational and accepting deposits.',
                'type' => 'info',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}',
                'action_text' => 'View RVM Details',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Status Changed to Inactive',
                'message' => 'RVM {rvm_name} has gone offline or is not operational. Please check the connection.',
                'type' => 'alert',
                'priority' => 'high',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}',
                'action_text' => 'Check RVM Status',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Under Maintenance',
                'message' => 'RVM {rvm_name} has been placed under maintenance mode.',
                'type' => 'info',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}',
                'action_text' => 'View Maintenance Details',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Error Detected',
                'message' => 'RVM {rvm_name} has encountered an error and requires immediate attention.',
                'type' => 'alert',
                'priority' => 'critical',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}',
                'action_text' => 'Resolve Error',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Storage Full',
                'message' => 'RVM {rvm_name} storage is full and needs to be emptied.',
                'type' => 'alert',
                'priority' => 'high',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}',
                'action_text' => 'Schedule Emptying',
                'is_active' => true,
                'created_by' => 1,
            ],

            // RVM Connection Status Notifications (High Priority)
            [
                'title' => 'RVM Connected',
                'message' => 'RVM {rvm_name} has successfully connected to the network.',
                'type' => 'info',
                'priority' => 'low',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}',
                'action_text' => 'View Connection Details',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Disconnected',
                'message' => 'RVM {rvm_name} has lost network connection. Please check connectivity.',
                'type' => 'alert',
                'priority' => 'high',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}',
                'action_text' => 'Check Connection',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Connection Unstable',
                'message' => 'RVM {rvm_name} is experiencing intermittent connection issues.',
                'type' => 'alert',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}',
                'action_text' => 'Diagnose Connection',
                'is_active' => true,
                'created_by' => 1,
            ],

            // RVM Capacity Alert Notifications (High Priority)
            [
                'title' => 'RVM Near Full Capacity',
                'message' => 'RVM {rvm_name} is at 80% capacity and will need emptying soon.',
                'type' => 'alert',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}',
                'action_text' => 'Schedule Maintenance',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Low Capacity Alert',
                'message' => 'RVM {rvm_name} capacity has dropped below 20%. Consider checking for issues.',
                'type' => 'info',
                'priority' => 'low',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}',
                'action_text' => 'View Capacity Details',
                'is_active' => true,
                'created_by' => 1,
            ],

            // RVM Health Monitoring Notifications (Medium Priority)
            [
                'title' => 'RVM Health Check Failed',
                'message' => 'Health check for RVM {rvm_name} has failed. System may not be responding properly.',
                'type' => 'alert',
                'priority' => 'high',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/monitoring',
                'action_text' => 'View Health Status',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Pulse Check Failed',
                'message' => 'Pulse check for RVM {rvm_name} has failed. Device may be unresponsive.',
                'type' => 'alert',
                'priority' => 'high',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/monitoring',
                'action_text' => 'Check Device Status',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM System Metrics Alert',
                'message' => 'System metrics for RVM {rvm_name} show unusual patterns. Please review.',
                'type' => 'alert',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/metrics',
                'action_text' => 'View Metrics',
                'is_active' => true,
                'created_by' => 1,
            ],

            // RVM Backup Operation Notifications (Medium Priority)
            [
                'title' => 'RVM Backup Started',
                'message' => 'Backup process for RVM {rvm_name} has been initiated.',
                'type' => 'info',
                'priority' => 'low',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/backup',
                'action_text' => 'Monitor Backup',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Backup Completed',
                'message' => 'Backup for RVM {rvm_name} has been completed successfully.',
                'type' => 'info',
                'priority' => 'low',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/backup',
                'action_text' => 'View Backup Details',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Backup Failed',
                'message' => 'Backup process for RVM {rvm_name} has failed. Please check the system.',
                'type' => 'alert',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/backup',
                'action_text' => 'Retry Backup',
                'is_active' => true,
                'created_by' => 1,
            ],

            // RVM Remote Access Notifications (Medium Priority)
            [
                'title' => 'RVM Remote Access Session Started',
                'message' => 'Remote access session for RVM {rvm_name} has been initiated by {user_name}.',
                'type' => 'info',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/remote-access',
                'action_text' => 'Monitor Session',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Remote Access Session Ended',
                'message' => 'Remote access session for RVM {rvm_name} has been terminated.',
                'type' => 'info',
                'priority' => 'low',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/remote-access',
                'action_text' => 'View Session Log',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'Unauthorized RVM Access Attempt',
                'message' => 'Unauthorized access attempt detected for RVM {rvm_name}. Security review required.',
                'type' => 'alert',
                'priority' => 'critical',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/security',
                'action_text' => 'Review Security',
                'is_active' => true,
                'created_by' => 1,
            ],

            // RVM Detection Result Notifications (Medium Priority)
            [
                'title' => 'RVM Detection Completed',
                'message' => 'Object detection for RVM {rvm_name} has been completed with {detection_count} items detected.',
                'type' => 'info',
                'priority' => 'low',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/detection',
                'action_text' => 'View Results',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Detection Failed',
                'message' => 'Object detection process for RVM {rvm_name} has failed. Please check the system.',
                'type' => 'alert',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/detection',
                'action_text' => 'Troubleshoot Detection',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'Unusual Detection Pattern',
                'message' => 'RVM {rvm_name} is showing unusual detection patterns. Manual review recommended.',
                'type' => 'alert',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/detection',
                'action_text' => 'Review Patterns',
                'is_active' => true,
                'created_by' => 1,
            ],

            // RVM Software Update Notifications (Medium Priority)
            [
                'title' => 'RVM Software Update Available',
                'message' => 'A new software update is available for RVM {rvm_name}.',
                'type' => 'info',
                'priority' => 'low',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/ota',
                'action_text' => 'Install Update',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Software Update Started',
                'message' => 'Software update for RVM {rvm_name} has been initiated.',
                'type' => 'info',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/ota',
                'action_text' => 'Monitor Update',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Software Update Completed',
                'message' => 'Software update for RVM {rvm_name} has been completed successfully.',
                'type' => 'info',
                'priority' => 'low',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/ota',
                'action_text' => 'View Update Details',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Software Update Failed',
                'message' => 'Software update for RVM {rvm_name} has failed. Manual intervention required.',
                'type' => 'alert',
                'priority' => 'high',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/ota',
                'action_text' => 'Retry Update',
                'is_active' => true,
                'created_by' => 1,
            ],

            // RVM Session Notifications (Low Priority)
            [
                'title' => 'RVM Session Started',
                'message' => 'A new user session has started on RVM {rvm_name}.',
                'type' => 'info',
                'priority' => 'low',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/sessions',
                'action_text' => 'View Session',
                'is_active' => false, // Disabled by default due to high frequency
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Session Completed',
                'message' => 'User session on RVM {rvm_name} has been completed successfully.',
                'type' => 'info',
                'priority' => 'low',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/sessions',
                'action_text' => 'View Session Details',
                'is_active' => false, // Disabled by default due to high frequency
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Session Timeout',
                'message' => 'User session on RVM {rvm_name} has timed out due to inactivity.',
                'type' => 'alert',
                'priority' => 'low',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/sessions',
                'action_text' => 'View Session Log',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Session Error',
                'message' => 'An error occurred during user session on RVM {rvm_name}.',
                'type' => 'alert',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/sessions',
                'action_text' => 'Investigate Error',
                'is_active' => true,
                'created_by' => 1,
            ],

            // RVM Deposit Notifications (Low Priority)
            [
                'title' => 'RVM Deposit Completed',
                'message' => 'A deposit has been completed successfully on RVM {rvm_name}.',
                'type' => 'info',
                'priority' => 'low',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/deposits',
                'action_text' => 'View Deposit',
                'is_active' => false, // Disabled by default due to high frequency
                'created_by' => 1,
            ],
            [
                'title' => 'RVM Deposit Failed',
                'message' => 'A deposit attempt on RVM {rvm_name} has failed. Please investigate.',
                'type' => 'alert',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/deposits',
                'action_text' => 'Investigate Failure',
                'is_active' => true,
                'created_by' => 1,
            ],
            [
                'title' => 'Unusual Deposit Activity',
                'message' => 'RVM {rvm_name} is showing unusual deposit activity patterns. Review recommended.',
                'type' => 'alert',
                'priority' => 'medium',
                'target_audience' => 'admins',
                'action_url' => '/admin/rvm/{rvm_id}/analytics',
                'action_text' => 'Review Activity',
                'is_active' => true,
                'created_by' => 1,
            ],
        ];

        foreach ($notifications as $notification) {
            SystemNotification::create($notification);
        }

        $this->command->info('RVM notification categories seeded successfully!');
    }
}
